<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.practicum</groupId>
        <artifactId>practicum-test-project</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>ru.practicum.logging</groupId>
    <artifactId>practicum-logging</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.13</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <configuration> <!-- Раздел настроек плагина -->
                    <descriptorRefs> <!-- Раздел в котором перечисляются дескрипторы, описывающие, что и как нужно упаковывать -->
                        <!-- Используем готовый дескриптор в составе плагина, который формирует jar-файл с классами внешних зависимостей -->
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive> <!-- Настройки jar-файла -->
                        <manifest>
                            <mainClass> <!-- Указываем входную точку приложения -->
                                ru.practicum.logging.LoggingDemo
                            </mainClass>
                        </manifest>
                    </archive>
                </configuration>

                <executions> <!-- Настраиваем когда плагин будет запускаться -->
                    <execution> <!-- У нас будет только один запуск, поэтому мы описываем только один элемент execution -->
                        <phase>package</phase> <!-- Плагин будет запускаться в фазе package, которая относится к циклу Default -->
                        <goals>
                            <goal>single</goal> <!-- Во время фазы package должна отработать цель single, которую предоставляет плагин -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>